version: '3'
services:
  worker:
    build: ./worker
    env_file:
      - .env
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    environment:
      - _JAVA_OPTIONS=-Xmx400M
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=password
