name: 'Check updates and build'

on:
  workflow_dispatch:
  push:
    paths:
      - 'worker/**'

permissions:
  contents: write
  packages: write

jobs:
  build-worker:
    name: Build worker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout files

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: worker
          platforms: linux/amd64
          tags: ghcr.io/pmh-only/projfn:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  build-nodelink:
    name: Build nodelink image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout files

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: nodelink
          platforms: linux/amd64
          tags: ghcr.io/pmh-only/nodelink:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

